version: "3"
services:
  testcafe:
    image: testcafe/testcafe
    volumes:
    - ./tests:/tests
    - ./screenshots:/screenshots
    command: chromium /tests/* --no-sandbox --screenshots /screenshots
